# Generated by Django 5.1.4 on 2026-10-04 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Internal campaign name, e.g. 'BYOS ₹799 Weekend Sale'", max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('title', models.CharField(blank=True, default='', help_text="Main heading e.g. 'BYOS'", max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', help_text="e.g. 'pick any 3 at'", max_length=200)),
                ('price_text', models.CharField(blank=True, default='', help_text="e.g. '₹799/-'", max_length=100)),
                ('supporting_text', models.TextField(blank=True, default='', help_text="e.g. '+ free shipping\\n+ free gift'")),
                ('cta_text', models.CharField(blank=True, default='SHOP NOW', max_length=100)),
                ('cta_url', models.CharField(blank=True, default='/shop', max_length=500)),
                ('desktop_image_url', models.CharField(blank=True, default='', help_text='Desktop artwork URL', max_length=1000)),
                ('mobile_image_url', models.CharField(blank=True, default='', help_text='Mobile artwork URL', max_length=1000)),
                ('background_image_url', models.CharField(blank=True, default='', help_text='Optional background', max_length=1000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(db_index=True, default=10, help_text='Higher number = higher precedence')),
                ('start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('display_order', models.IntegerField(db_index=True, default=0)),
                ('layer_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'db_table': 'promotional_banners',
                'ordering': ['-priority', 'display_order', '-created_at'],
                'indexes': [models.Index(fields=['status', 'is_active', 'start_at', 'end_at', 'priority'], name='idx_promo_banner_active'), models.Index(fields=['priority', 'display_order'], name='idx_promo_banner_prio_ord')],
            },
        ),
        migrations.CreateModel(
            name='PromotionalBannerAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('hero', 'Hero'), ('background', 'Background'), ('product', 'Product'), ('decoration', 'Decoration'), ('model', 'Model'), ('badge', 'Badge'), ('mobile', 'Mobile Artwork'), ('desktop', 'Desktop Artwork')], default='hero', max_length=50)),
                ('asset_url', models.CharField(max_length=1000)),
                ('storage_path', models.CharField(blank=True, default='', max_length=500)),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='banners.promotionalbanner')),
            ],
            options={
                'db_table': 'promotional_banner_assets',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
