services:
  - type: web
    name: jewlsnjoy-backend
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: CORS_ALLOW_ALL
        value: "True"
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,.onrender.com"
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_ENV
        value: "test"
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
      - key: SUPABASE_URL
        value: "https://hlxffdtkghzednkpwxlb.supabase.co"
      - key: SUPABASE_PUBLISHABLE_KEY
        value: "sb_publishable_Q7YuMERgjfL5BcbmeBvGQw_irH77xJQ"
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: SUPABASE_STORAGE_BUCKET
        value: "payment-proofs"
