# Generated by Django 5.1.4 on 2026-09-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('badge_label', models.CharField(blank=True, default='Strict Policy', max_length=100)),
                ('last_updated', models.CharField(blank=True, default='', max_length=100)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Store Policies',
                'ordering': ['key'],
            },
        ),
    ]
