# Generated by Django 5.1.4 on 2026-09-20 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_storepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_email',
            field=models.EmailField(blank=True, default='', help_text='Email for guest review verification', max_length=254),
        ),
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Admin can moderate reviews before display'),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order associated with this review for purchase verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='products.order'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Supabase user ID of the reviewer', max_length=64),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_verified_buyer',
            field=models.BooleanField(default=False, help_text='True if reviewer purchased this product'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('user_id', ''), _negated=True), fields=('product', 'user_id'), name='unique_authenticated_user_review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('author_email', ''), _negated=True), fields=('product', 'author_email'), name='unique_guest_email_review'),
        ),
    ]
