# Generated by Django 5.1.4 on 2026-09-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_review_author_email_review_is_approved_review_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Store Customizations',
                'ordering': ['key'],
            },
        ),
    ]
