# Generated by Django 5.1.4 on 2026-09-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_storecustomization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_image_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
    ]
