# Generated by Django 5.1.4 on 2026-09-07 15:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_alter_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, default='delhivery', help_text="Logistics carrier (e.g. 'delhivery')", max_length=50)),
                ('provider_order_id', models.CharField(blank=True, default='', help_text="Carrier's internal order/upload reference ID.", max_length=100)),
                ('provider_shipment_id', models.CharField(blank=True, default='', help_text="Carrier's package or shipment identifier.", max_length=100)),
                ('awb_number', models.CharField(blank=True, db_index=True, default='', help_text='Air Waybill / tracking number assigned by Delhivery.', max_length=100)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=100)),
                ('shipment_status', models.CharField(choices=[('manifested', 'Manifested / Ready for Pickup'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('rto_initiated', 'RTO Initiated'), ('rto_delivered', 'RTO Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Shipment Failed')], db_index=True, default='manifested', help_text='Normalized shipment status.', max_length=50)),
                ('provider_status', models.CharField(blank=True, default='', help_text='Exact status string returned by Delhivery API.', max_length=100)),
                ('provider_status_code', models.CharField(blank=True, default='', help_text="Short status code from carrier scans (e.g. 'UD', 'DL').", max_length=50)),
                ('payment_mode', models.CharField(choices=[('Prepaid', 'Prepaid'), ('COD', 'Cash on Delivery (COD)')], default='Prepaid', max_length=20)),
                ('cod_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Exact amount payable by customer at delivery (0.00 for prepaid).', max_digits=12)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Operational carrier freight cost quoted by Delhivery.', max_digits=10, null=True)),
                ('weight_grams', models.PositiveIntegerField(default=200, help_text='Dead or volumetric weight in grams.')),
                ('length_cm', models.DecimalField(decimal_places=2, default=Decimal('10.0'), max_digits=6)),
                ('breadth_cm', models.DecimalField(decimal_places=2, default=Decimal('10.0'), max_digits=6)),
                ('height_cm', models.DecimalField(decimal_places=2, default=Decimal('5.0'), max_digits=6)),
                ('pickup_location', models.CharField(blank=True, default='', help_text='Registered warehouse name in Delhivery One.', max_length=200)),
                ('pickup_token_number', models.CharField(blank=True, default='', help_text='Pickup request token number returned by Delhivery.', max_length=100)),
                ('label_url', models.CharField(blank=True, default='', help_text='URL to print or download Delhivery packing slip / barcode label.', max_length=500)),
                ('tracking_url', models.CharField(blank=True, default='', help_text='Public carrier tracking portal link.', max_length=500)),
                ('provider_response', models.JSONField(blank=True, default=dict, help_text='Sanitized snapshot of carrier creation/tracking response.')),
                ('tracking_events', models.JSONField(blank=True, default=list, help_text='List of normalized tracking checkpoint scans.')),
                ('ndr_status', models.CharField(blank=True, default='', max_length=50)),
                ('ndr_reason', models.CharField(blank=True, default='', max_length=255)),
                ('ndr_attempt_count', models.PositiveIntegerField(default=0)),
                ('last_ndr_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Last logged operational or carrier error message.')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(help_text='The customer order associated with this shipment.', on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='products.order')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
