# Generated by Django 5.1.4 on 2026-09-06 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_remove_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('cashfree_order_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('signature', models.CharField(blank=True, default='', max_length=255)),
                ('is_valid_signature', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashfree_order_id', models.CharField(db_index=True, max_length=100)),
                ('cashfree_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('payment_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=30)),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='products.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
