# Generated by Django 5.1.4 on 2026-09-07 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttransaction_razorpay_order_id_and_more'),
        ('products', '0007_alter_order_payment_status_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('payment_method', models.CharField(default='manual_upi', max_length=50)),
                ('transaction_id', models.CharField(db_index=True, max_length=100)),
                ('payment_proof_path', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending_verification', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payment_verifications', to='products.order')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_manual_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='payments_pa_transac_9b9091_idx'), models.Index(fields=['status'], name='payments_pa_status_639e46_idx'), models.Index(fields=['user_id'], name='payments_pa_user_id_8ae2da_idx')],
            },
        ),
    ]
