"""
Mock product data for Jewels N' Joys.
7 real jewelry items with multi-angle photography.
"""

PRODUCTS = [
    {
        "id": 1,
        "name": "Emerald Luxe Tennis Necklace",
        "slug": "emerald-luxe-tennis-necklace",
        "price": 799,
        "original_price": 999,
        "category": "Necklaces",
        "style": ["Elegant", "Luxury"],
        "short_description": "A sophisticated gold-tone herringbone necklace accented with vivid square-cut green decorative stones.",
        "description": "A sophisticated gold-tone herringbone necklace accented with multiple vivid green square-cut decorative stones. The sleek flat chain combined with emerald-green accents creates an opulent statement suitable for both everyday styling and grand occasions.",
        "image": "/api/placeholder/product_1/1",
        "thumbnail": "/api/placeholder/product_1/1",
        "images": [
            "/api/placeholder/product_1/1",
            "/api/placeholder/product_1/2",
            "/api/placeholder/product_1/3",
        ],
        "variants": [],
        "in_stock": True,
        "is_featured": True,
        "is_bestseller": True,
        "rating": 4.9,
        "review_count": 142,
        "features": ["Anti-tarnish", "Waterproof", "PVD Plated", "18K Gold Plated"],
        "specifications": {
            "Material": "Titanium Stainless Steel",
            "Finish": "18K Gold Color Plated",
            "Plating": "Long-lasting PVD Plated",
            "Stones": "Emerald-Green Decorative Stones",
            "Features": "Anti-tarnish, Waterproof, Quality Guarantee",
        },
        "shipping": {
            "standard": "3–5 business days",
            "express": "1–2 business days",
            "free_threshold": 999,
        },
        "care_instructions": [
            "Avoid direct contact with harsh perfumes and chemicals.",
            "Store in the provided jewellery pouch when not in use.",
            "Clean gently with a soft dry cloth.",
        ],
    },
    {
        "id": 2,
        "name": "Midnight Heart Pendant Necklace",
        "slug": "midnight-heart-pendant-necklace",
        "price": 599,
        "original_price": 749,
        "category": "Necklaces",
        "style": ["Minimal", "Romantic"],
        "short_description": "A minimalist gold-tone heart necklace featuring a glossy black heart centerpiece framed by polished gold.",
        "description": "A minimalist gold-tone heart necklace featuring a glossy black heart centerpiece framed by a polished gold heart bezel. Its sleek silhouette makes it effortless to style with casual outfits, evening wear, and everyday looks.",
        "image": "/api/placeholder/product_2/1",
        "thumbnail": "/api/placeholder/product_2/1",
        "images": [
            "/api/placeholder/product_2/1",
            "/api/placeholder/product_2/2",
            "/api/placeholder/product_2/3",
            "/api/placeholder/product_2/4",
            "/api/placeholder/product_2/5",
        ],
        "variants": [],
        "in_stock": True,
        "is_featured": True,
        "is_bestseller": True,
        "rating": 4.8,
        "review_count": 98,
        "features": ["Anti-tarnish", "Waterproof", "PVD Plated", "Glossy Onyx Heart"],
        "specifications": {
            "Material": "Titanium Stainless Steel",
            "Finish": "18K Gold Color Plated",
            "Plating": "Long-lasting PVD Plated",
            "Stones": "Glossy Black Onyx Heart",
            "Features": "Anti-tarnish, Waterproof, Quality Guarantee",
        },
        "shipping": {
            "standard": "3–5 business days",
            "express": "1–2 business days",
            "free_threshold": 999,
        },
        "care_instructions": [
            "Avoid direct contact with harsh perfumes and chemicals.",
            "Store in the provided jewellery pouch when not in use.",
            "Clean gently with a soft dry cloth.",
        ],
    },
    {
        "id": 3,
        "name": "Royal Crown Pink Crystal Necklace",
        "slug": "royal-crown-pink-crystal-necklace",
        "price": 649,
        "original_price": 799,
        "category": "Necklaces",
        "style": ["Romantic", "Statement"],
        "short_description": "An enchanting silver-tone necklace showcasing a regal crown perched atop a faceted pink heart zircon crystal.",
        "description": "An enchanting silver-tone necklace showcasing a regal crown accented with clear crystals perched atop a vivid faceted pink heart zircon. A delicate titanium steel chain ensures lasting brilliance and comfort for any royal occasion.",
        "image": "/api/placeholder/product_3/1",
        "thumbnail": "/api/placeholder/product_3/1",
        "images": [
            "/api/placeholder/product_3/1",
            "/api/placeholder/product_3/2",
            "/api/placeholder/product_3/3",
            "/api/placeholder/product_3/4",
            "/api/placeholder/product_3/5",
        ],
        "variants": [],
        "in_stock": True,
        "is_featured": True,
        "is_bestseller": False,
        "rating": 4.7,
        "review_count": 76,
        "features": ["Anti-tarnish", "Waterproof", "Rhodium Plated", "Faceted Zircon"],
        "specifications": {
            "Material": "Titanium Stainless Steel Chain, Copper Pendant",
            "Finish": "Rhodium Color Plated",
            "Plating": "Long-lasting PVD Plated",
            "Stones": "High Quality Pink Zircon Crystal",
            "Features": "Anti-tarnish, Waterproof, Quality Guarantee",
        },
        "shipping": {
            "standard": "3–5 business days",
            "express": "1–2 business days",
            "free_threshold": 999,
        },
        "care_instructions": [
            "Avoid direct contact with harsh perfumes and chemicals.",
            "Store in the provided jewellery pouch when not in use.",
            "Clean gently with a soft dry cloth.",
        ],
    },
    {
        "id": 4,
        "name": "Onyx Solitaire Medallion Necklace",
        "slug": "onyx-solitaire-medallion-necklace",
        "price": 699,
        "original_price": 849,
        "category": "Necklaces",
        "style": ["Vintage", "Classic"],
        "short_description": "A vintage-inspired oval medallion necklace featuring a deep faceted onyx stone in a sunburst gold bezel setting.",
        "description": "A striking vintage-inspired oval medallion necklace featuring a deep faceted black stone set in an architectural sunburst gold bezel. Suspended on a durable gold cable chain with extender.",
        "image": "/api/placeholder/product_4/1",
        "thumbnail": "/api/placeholder/product_4/1",
        "images": [
            "/api/placeholder/product_4/1",
            "/api/placeholder/product_4/2",
            "/api/placeholder/product_4/3",
            "/api/placeholder/product_4/4",
            "/api/placeholder/product_4/5",
        ],
        "variants": [],
        "in_stock": True,
        "is_featured": False,
        "is_bestseller": False,
        "rating": 4.9,
        "review_count": 64,
        "features": ["316L Steel", "Anti-tarnish", "Waterproof", "Faceted Onyx"],
        "specifications": {
            "Material": "316L Stainless Steel",
            "Weight": "3.6g",
            "Length": "40cm + 5cm extension",
            "PendantSize": "1.2cm",
            "Finish": "18K Gold Plated",
            "Stones": "Faceted Black Onyx Stone",
            "Features": "Anti-tarnish, Waterproof",
        },
        "shipping": {
            "standard": "3–5 business days",
            "express": "1–2 business days",
            "free_threshold": 999,
        },
        "care_instructions": [
            "Avoid direct contact with harsh perfumes and chemicals.",
            "Store in the provided jewellery pouch when not in use.",
            "Clean gently with a soft dry cloth.",
        ],
    },
    {
        "id": 5,
        "name": "Reversible Four-Leaf Clover Necklace",
        "slug": "reversible-four-leaf-clover-necklace",
        "price": 749,
        "original_price": 899,
        "category": "Necklaces",
        "style": ["Modern", "Lucky", "Versatile"],
        "short_description": "An iconic four-leaf clover pendant necklace featuring a reversible design with onyx black on one side and mother-of-pearl white on the other.",
        "description": "An iconic four-leaf clover pendant necklace featuring a reversible two-in-one design: onyx black on one side and iridescent mother-of-pearl white on the other, framed in a sparkling crystal pavé halo.",
        "image": "/api/placeholder/product_5/1",
        "thumbnail": "/api/placeholder/product_5/1",
        "images": [
            "/api/placeholder/product_5/1",
            "/api/placeholder/product_5/2",
            "/api/placeholder/product_5/3",
            "/api/placeholder/product_5/4",
            "/api/placeholder/product_5/5",
        ],
        "variants": [],
        "in_stock": True,
        "is_featured": True,
        "is_bestseller": True,
        "rating": 5.0,
        "review_count": 185,
        "features": ["Reversible 2-in-1", "Anti-tarnish", "Waterproof", "Pavé Halo"],
        "specifications": {
            "Material": "Titanium Stainless Steel",
            "Finish": "18K Gold Color Plated",
            "Plating": "Long-lasting PVD Plated",
            "Stones": "Reversible Black/White Inlay & Pavé Zircons",
            "Features": "Reversible 2-in-1, Anti-tarnish, Waterproof, Quality Guarantee",
        },
        "shipping": {
            "standard": "3–5 business days",
            "express": "1–2 business days",
            "free_threshold": 999,
        },
        "care_instructions": [
            "Avoid direct contact with harsh perfumes and chemicals.",
            "Store in the provided jewellery pouch when not in use.",
            "Clean gently with a soft dry cloth.",
        ],
    },
    {
        "id": 6,
        "name": "Emerald Square Layered Duo Necklace",
        "slug": "emerald-square-layered-duo-necklace",
        "price": 849,
        "original_price": 1049,
        "category": "Necklaces",
        "style": ["Layered", "Contemporary"],
        "short_description": "A curated two-strand necklace pairing a sleek herringbone chain with a crystal drop and a delicate cable chain holding an emerald halo pendant.",
        "description": "A perfectly curated two-strand necklace featuring a sleek herringbone chain accented with a round solitaire crystal, layered effortlessly with a delicate cable chain carrying a halo-framed square emerald pendant.",
        "image": "/api/placeholder/product_6/1",
        "thumbnail": "/api/placeholder/product_6/1",
        "images": [
            "/api/placeholder/product_6/1",
            "/api/placeholder/product_6/2",
            "/api/placeholder/product_6/3",
            "/api/placeholder/product_6/4",
            "/api/placeholder/product_6/5",
        ],
        "variants": [],
        "in_stock": True,
        "is_featured": True,
        "is_bestseller": True,
        "rating": 4.9,
        "review_count": 110,
        "features": ["Double Layer Chain", "Anti-tarnish", "Waterproof", "Emerald Crystal"],
        "specifications": {
            "Material": "316L Stainless Steel",
            "Finish": "18K Gold & Platinum Plated",
            "Plating": "Long-lasting PVD Plated",
            "Stones": "Square Cut Emerald Stone & Solitaire Crystal",
            "Features": "Double Layer Chain, Anti-tarnish, Waterproof, Quality Guarantee",
        },
        "shipping": {
            "standard": "3–5 business days",
            "express": "1–2 business days",
            "free_threshold": 999,
        },
        "care_instructions": [
            "Avoid direct contact with harsh perfumes and chemicals.",
            "Store in the provided jewellery pouch when not in use.",
            "Clean gently with a soft dry cloth.",
        ],
    },
    {
        "id": 7,
        "name": "Emerald Sovereign Herringbone Choker",
        "slug": "emerald-sovereign-herringbone-choker",
        "price": 899,
        "original_price": 1099,
        "category": "Necklaces",
        "style": ["Luxury", "Statement"],
        "short_description": "A statement flat herringbone chain choker centered with a lavish oval emerald stone set in ribbed gold caps.",
        "description": "A statement flat herringbone chain choker centered with a lavish oval emerald green gemstone hugged by sculpted, ribbed gold end-caps. Crafted to sit flawlessly along the collarbone with liquid-gold movement.",
        "image": "/api/placeholder/product_7/1",
        "thumbnail": "/api/placeholder/product_7/1",
        "images": [
            "/api/placeholder/product_7/1",
            "/api/placeholder/product_7/2",
            "/api/placeholder/product_7/3",
            "/api/placeholder/product_7/4",
        ],
        "variants": [],
        "in_stock": True,
        "is_featured": True,
        "is_bestseller": True,
        "rating": 4.9,
        "review_count": 135,
        "features": ["Herringbone Choker", "Anti-tarnish", "Waterproof", "Oval Emerald Stone"],
        "specifications": {
            "Material": "Titanium Stainless Steel",
            "Finish": "18K Gold Color Plated",
            "Plating": "Long-lasting PVD Plated",
            "Stones": "Oval Cut Emerald Stone",
            "Features": "Anti-tarnish, Waterproof, Quality Guarantee",
        },
        "shipping": {
            "standard": "3–5 business days",
            "express": "1–2 business days",
            "free_threshold": 999,
        },
        "care_instructions": [
            "Avoid direct contact with harsh perfumes and chemicals.",
            "Store in the provided jewellery pouch when not in use.",
            "Clean gently with a soft dry cloth.",
        ],
    },
]

CATEGORIES = [
    {
        "id": 1,
        "name": "Necklaces",
        "slug": "necklaces",
        "description": "Handcrafted chains, chokers, and pendant necklaces designed to elevate your everyday elegance.",
        "image": "/api/placeholder/product_1/1",
        "product_count": 7,
    },
    {
        "id": 2,
        "name": "Earrings",
        "slug": "earrings",
        "description": "Twist hoops, drop studs, and statement earrings crafted with durable PVD plating.",
        "image": "/api/placeholder/product_3/1",
        "product_count": 0,
    },
    {
        "id": 3,
        "name": "Rings",
        "slug": "rings",
        "description": "Star-burst signets and minimalist stackable bands made for everyday wear.",
        "image": "/api/placeholder/product_5/1",
        "product_count": 0,
    },
]
